language: node_js
sudo: false
script: gulp travis
node_js:
  - "4"
env:
  - KARMA_BROWSER=firefox

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start

cache:
  directories:
    - node_modules
